spring:
  datasource:
    url: jdbc:postgresql://dpg-d2orbg7diees73fpih3g-a.oregon-postgres.render.com:5432/badge_db_mrvn
    username: badge_db_mrvn_user
    password: dshw6vOj8SVBi9bVggBkS8P5OKRLEWcl
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:lgustavog27@gmail.com}
    password: ${MAIL_PASSWORD:zeig ziqn zmex yjna}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    com.badgegenerator: DEBUG
    org.springframework.mail: DEBUG

app:
  upload:
    dir: uploads/
  badge:
    template-path: templates/badge-template.html

uploads:
  badges: uploads/badges
  issuers: uploads/issuers