spring:
  datasource:
    url: jdbc:mysql://localhost:3306/badge_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: gustavo27
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:lgustavog27@gmail.com}
    password: ${MAIL_PASSWORD:zeig ziqn zmex yjna}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

logging:
  level:
    com.badgegenerator: DEBUG
    org.springframework.mail: DEBUG

app:
  upload:
    dir: uploads/
  badge:
    template-path: templates/badge-template.html